version: '2'
services:

  rabbitmq:
    image: rabbitmq:3.6.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=muon
      - RABBITMQ_DEFAULT_PASS=microservices
    expose:
      - "5672"
      - "15672"

  photon:
    image: simplicityitself-muon-image.jfrog.io/photon
    environment:
      - MUON_URL=amqp://muon:microservices@rabbitmq
    links:
      - rabbitmq
    command: -jar target/photon.jar -rest.host 0.0.0.0

# Test Clients
  password-service:
    image: simplicityitself-muon-image.jfrog.io/aether-password
    external_links:
      - rabbitmq
    volumes:
      - ./test-results/:/applocal/output

  core-service-test:
    image: simplicityitself-muon-image.jfrog.io/aether-core
    external_links:
      - rabbitmq
    volumes:
      - ./test-results/:/applocal/output
